// src/app/layout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer'; // Import the Footer

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'MK3 App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="flex-grow">{children}</main> {/* main usually takes up remaining space */}
        <Footer /> {/* Your Footer component */}
      </body>
    </html>
  );
}